### ISSUE TITLE
Define subSet

### ISSUE THREAD

**Issue by teqnickels** [GuildCrafts/core-data-structures#84]
For set, I spent a  lot of time defining whether subset was "more than one number" of the small set or every number in the smaller set, or any number from the smaller set. What qualifies as a subset?

**Comment by tannerwelsh** [comment]
@teqnickels thanks for this feedback! I added this line to the "Set" section:

_Note: if you haven't worked with sets before, you may want to read about [sets](https://www.mathsisfun.com/sets/sets-introduction.html) and [subsets](https://www.mathsisfun.com/activity/subsets.html)._
