### ISSUE TITLE
Goal spec length reduction

### ISSUE THREAD

**Issue by AbrahamFergie** [GuildCrafts/core-data-structures#89]
I have gotten some feedback about how this goal is too much for learners to complete, I know this goal has already been split up between 156 and 157 but for a lot of people here they are getting used to how to navigate collaborative problem solving. I would like to propose that we keep this goal but add the option of being able to choose to do either the basic or the advanced structures and have that clearly stated in the specs.

**Comment by tannerwelsh** [comment]
Thanks for the feedback @AbrahamFergie. Addressed with https://github.com/GuildCrafts/web-development-js/commit/bb0a571e17163d901b6eaf6bb913a87645231445 (156 - basic version - is 2 person, this one is moved to level 2)
